// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_module_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        u_perm,
        u_perm_c_din,
        u_perm_c_num_data_valid,
        u_perm_c_fifo_cap,
        u_perm_c_full_n,
        u_perm_c_write,
        u_diff,
        u_diff_c_din,
        u_diff_c_num_data_valid,
        u_diff_c_fifo_cap,
        u_diff_c_full_n,
        u_diff_c_write,
        u_dt,
        u_dt_c_din,
        u_dt_c_num_data_valid,
        u_dt_c_fifo_cap,
        u_dt_c_full_n,
        u_dt_c_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] u_perm;
output  [31:0] u_perm_c_din;
input  [3:0] u_perm_c_num_data_valid;
input  [3:0] u_perm_c_fifo_cap;
input   u_perm_c_full_n;
output   u_perm_c_write;
input  [31:0] u_diff;
output  [31:0] u_diff_c_din;
input  [3:0] u_diff_c_num_data_valid;
input  [3:0] u_diff_c_fifo_cap;
input   u_diff_c_full_n;
output   u_diff_c_write;
input  [31:0] u_dt;
output  [31:0] u_dt_c_din;
input  [3:0] u_dt_c_num_data_valid;
input  [3:0] u_dt_c_fifo_cap;
input   u_dt_c_full_n;
output   u_dt_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg u_perm_c_write;
reg u_diff_c_write;
reg u_dt_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    u_perm_c_blk_n;
reg    u_diff_c_blk_n;
reg    u_dt_c_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (u_dt_c_full_n == 1'b0) | (u_diff_c_full_n == 1'b0) | (u_perm_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (u_dt_c_full_n == 1'b0) | (u_diff_c_full_n == 1'b0) | (u_perm_c_full_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (u_dt_c_full_n == 1'b0) | (u_diff_c_full_n == 1'b0) | (u_perm_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (u_dt_c_full_n == 1'b0) | (u_diff_c_full_n == 1'b0) | (u_perm_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        u_diff_c_blk_n = u_diff_c_full_n;
    end else begin
        u_diff_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (u_dt_c_full_n == 1'b0) | (u_diff_c_full_n == 1'b0) | (u_perm_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        u_diff_c_write = 1'b1;
    end else begin
        u_diff_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        u_dt_c_blk_n = u_dt_c_full_n;
    end else begin
        u_dt_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (u_dt_c_full_n == 1'b0) | (u_diff_c_full_n == 1'b0) | (u_perm_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        u_dt_c_write = 1'b1;
    end else begin
        u_dt_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        u_perm_c_blk_n = u_perm_c_full_n;
    end else begin
        u_perm_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (u_dt_c_full_n == 1'b0) | (u_diff_c_full_n == 1'b0) | (u_perm_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        u_perm_c_write = 1'b1;
    end else begin
        u_perm_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (u_dt_c_full_n == 1'b0) | (u_diff_c_full_n == 1'b0) | (u_perm_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign u_diff_c_din = u_diff;

assign u_dt_c_din = u_dt;

assign u_perm_c_din = u_perm;

endmodule //top_module_entry_proc
