// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_module_preProcessing (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        msg_strm_dout,
        msg_strm_num_data_valid,
        msg_strm_fifo_cap,
        msg_strm_empty_n,
        msg_strm_read,
        len_strm_dout,
        len_strm_num_data_valid,
        len_strm_fifo_cap,
        len_strm_empty_n,
        len_strm_read,
        end_len_strm_dout,
        end_len_strm_num_data_valid,
        end_len_strm_fifo_cap,
        end_len_strm_empty_n,
        end_len_strm_read,
        blk_strm_din,
        blk_strm_num_data_valid,
        blk_strm_fifo_cap,
        blk_strm_full_n,
        blk_strm_write,
        nblk_strm_din,
        nblk_strm_num_data_valid,
        nblk_strm_fifo_cap,
        nblk_strm_full_n,
        nblk_strm_write,
        end_nblk_strm_din,
        end_nblk_strm_num_data_valid,
        end_nblk_strm_fifo_cap,
        end_nblk_strm_full_n,
        end_nblk_strm_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] msg_strm_dout;
input  [15:0] msg_strm_num_data_valid;
input  [15:0] msg_strm_fifo_cap;
input   msg_strm_empty_n;
output   msg_strm_read;
input  [63:0] len_strm_dout;
input  [1:0] len_strm_num_data_valid;
input  [1:0] len_strm_fifo_cap;
input   len_strm_empty_n;
output   len_strm_read;
input  [0:0] end_len_strm_dout;
input  [1:0] end_len_strm_num_data_valid;
input  [1:0] end_len_strm_fifo_cap;
input   end_len_strm_empty_n;
output   end_len_strm_read;
output  [511:0] blk_strm_din;
input  [13:0] blk_strm_num_data_valid;
input  [13:0] blk_strm_fifo_cap;
input   blk_strm_full_n;
output   blk_strm_write;
output  [63:0] nblk_strm_din;
input  [5:0] nblk_strm_num_data_valid;
input  [5:0] nblk_strm_fifo_cap;
input   nblk_strm_full_n;
output   nblk_strm_write;
output  [0:0] end_nblk_strm_din;
input  [5:0] end_nblk_strm_num_data_valid;
input  [5:0] end_nblk_strm_fifo_cap;
input   end_nblk_strm_full_n;
output   end_nblk_strm_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg msg_strm_read;
reg len_strm_read;
reg end_len_strm_read;
reg[511:0] blk_strm_din;
reg blk_strm_write;
reg nblk_strm_write;
reg[0:0] end_nblk_strm_din;
reg end_nblk_strm_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    len_strm_blk_n;
wire    ap_CS_fsm_state2;
reg    end_len_strm_blk_n;
wire    ap_CS_fsm_state9;
reg    blk_strm_blk_n;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln343_fu_315_p2;
wire    ap_CS_fsm_state8;
reg   [0:0] cmp116_reg_668;
reg   [0:0] icmp_ln343_reg_664;
reg    nblk_strm_blk_n;
reg    end_nblk_strm_blk_n;
reg    ap_block_state1;
reg   [63:0] len_reg_634;
reg    ap_block_state2;
wire   [5:0] left_fu_264_p1;
reg   [5:0] left_reg_641;
wire   [28:0] trunc_ln485_fu_268_p1;
reg   [28:0] trunc_ln485_reg_647;
wire   [57:0] trunc_ln_fu_272_p4;
reg   [57:0] trunc_ln_reg_654;
wire   [1:0] trunc_ln299_fu_286_p1;
reg   [1:0] trunc_ln299_reg_659;
reg    ap_block_state5;
wire   [0:0] cmp116_fu_320_p2;
wire   [0:0] rev_fu_374_p2;
reg   [0:0] rev_reg_673;
wire    ap_CS_fsm_state6;
reg   [2:0] trunc_ln375_1_reg_678;
wire   [3:0] select_ln375_fu_391_p3;
reg   [3:0] select_ln375_reg_683;
wire   [31:0] grp_fu_255_p4;
reg   [31:0] tmp_1_reg_688;
reg    ap_block_state8;
reg    ap_predicate_op102_write_state9;
reg    ap_block_state9;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_idle;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_ready;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_msg_strm_read;
wire   [511:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_din;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_write;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_idle;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_ready;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_msg_strm_read;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_18_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_18_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_17_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_17_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_16_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_16_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_15_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_15_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_14_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_14_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_13_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_13_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_12_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_12_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_11_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_11_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_10_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_10_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_9_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_9_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_8_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_8_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_7_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_7_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_6_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_6_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_5_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_5_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_4_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_4_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_out_ap_vld;
reg   [0:0] end_flag_3_reg_211;
reg    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg;
reg   [8:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg;
wire    ap_CS_fsm_state7;
wire   [511:0] or_ln365_1_fu_360_p2;
wire   [511:0] or_ln471_s_fu_447_p17;
wire   [511:0] or_ln467_s_fu_484_p18;
wire   [511:0] or_ln489_s_fu_522_p5;
wire   [0:0] icmp_ln299_fu_290_p2;
wire   [58:0] select_ln299_fu_296_p3;
wire   [58:0] zext_ln299_fu_282_p1;
wire   [58:0] blk_num_fu_304_p2;
wire   [511:0] or_ln_fu_325_p5;
wire   [511:0] or_ln365_fu_336_p2;
wire   [479:0] tmp_24_fu_342_p4;
wire   [511:0] or_ln365_s_fu_352_p3;
wire   [0:0] tmp_fu_367_p3;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_condition_155;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg = 1'b0;
#0 grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg = 1'b0;
end

top_module_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start),
    .ap_done(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done),
    .ap_idle(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_idle),
    .ap_ready(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_ready),
    .msg_strm_dout(msg_strm_dout),
    .msg_strm_num_data_valid(16'd0),
    .msg_strm_fifo_cap(16'd0),
    .msg_strm_empty_n(msg_strm_empty_n),
    .msg_strm_read(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_msg_strm_read),
    .trunc_ln(trunc_ln_reg_654),
    .blk_strm_din(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_din),
    .blk_strm_num_data_valid(14'd0),
    .blk_strm_fifo_cap(14'd0),
    .blk_strm_full_n(blk_strm_full_n),
    .blk_strm_write(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_write)
);

top_module_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start),
    .ap_done(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done),
    .ap_idle(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_idle),
    .ap_ready(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_ready),
    .msg_strm_dout(msg_strm_dout),
    .msg_strm_num_data_valid(16'd0),
    .msg_strm_fifo_cap(16'd0),
    .msg_strm_empty_n(msg_strm_empty_n),
    .msg_strm_read(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_msg_strm_read),
    .select_ln375(select_ln375_reg_683),
    .zext_ln375(trunc_ln375_1_reg_678),
    .trunc_ln299_1(trunc_ln299_reg_659),
    .cmp203(rev_reg_673),
    .b_18_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_18_out),
    .b_18_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_18_out_ap_vld),
    .b_17_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_17_out),
    .b_17_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_17_out_ap_vld),
    .b_16_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_16_out),
    .b_16_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_16_out_ap_vld),
    .b_15_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_15_out),
    .b_15_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_15_out_ap_vld),
    .b_14_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_14_out),
    .b_14_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_14_out_ap_vld),
    .b_13_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_13_out),
    .b_13_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_13_out_ap_vld),
    .b_12_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_12_out),
    .b_12_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_12_out_ap_vld),
    .b_11_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_11_out),
    .b_11_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_11_out_ap_vld),
    .b_10_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_10_out),
    .b_10_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_10_out_ap_vld),
    .b_9_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_9_out),
    .b_9_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_9_out_ap_vld),
    .b_8_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_8_out),
    .b_8_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_8_out_ap_vld),
    .b_7_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_7_out),
    .b_7_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_7_out_ap_vld),
    .b_6_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_6_out),
    .b_6_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_6_out_ap_vld),
    .b_5_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_5_out),
    .b_5_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_5_out_ap_vld),
    .b_4_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_4_out),
    .b_4_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_4_out_ap_vld),
    .b_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_out),
    .b_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg <= 1'b1;
        end else if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_ready == 1'b1)) begin
            grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_NS_fsm_state3))) begin
            grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg <= 1'b1;
        end else if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_ready == 1'b1)) begin
            grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((blk_strm_full_n == 1'b0) & (icmp_ln343_fu_315_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln343_fu_315_p2 == 1'd0))) begin
        cmp116_reg_668 <= cmp116_fu_320_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((end_len_strm_empty_n == 1'b0) | ((blk_strm_full_n == 1'b0) & (ap_predicate_op102_write_state9 == 1'b1))) & (1'b1 == ap_CS_fsm_state9)) | (~((end_len_strm_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        end_flag_3_reg_211 <= end_len_strm_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((blk_strm_full_n == 1'b0) & (icmp_ln343_fu_315_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5))) begin
        icmp_ln343_reg_664 <= icmp_ln343_fu_315_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        left_reg_641 <= left_fu_264_p1;
        len_reg_634 <= len_strm_dout;
        trunc_ln299_reg_659 <= trunc_ln299_fu_286_p1;
        trunc_ln485_reg_647 <= trunc_ln485_fu_268_p1;
        trunc_ln_reg_654 <= {{len_strm_dout[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        rev_reg_673 <= rev_fu_374_p2;
        select_ln375_reg_683 <= select_ln375_fu_391_p3;
        trunc_ln375_1_reg_678 <= {{len_reg_634[5:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~(((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd0)) | ((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd1))) & (1'b1 == ap_CS_fsm_state8) & (cmp116_reg_668 == 1'd0))) begin
        tmp_1_reg_688 <= {{len_reg_634[60:29]}};
    end
end

always @ (*) begin
    if (((end_len_strm_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0)))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((blk_strm_full_n == 1'b0) & (icmp_ln343_fu_315_p2 == 1'd1))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd0)) | ((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd1)))) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((end_len_strm_empty_n == 1'b0) | ((blk_strm_full_n == 1'b0) & (ap_predicate_op102_write_state9 == 1'b1)))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state8) & (cmp116_reg_668 == 1'd0)) | ((1'b1 == ap_CS_fsm_state8) & (cmp116_reg_668 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln343_fu_315_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln343_reg_664 == 1'd0) & (cmp116_reg_668 == 1'd0)))) begin
        blk_strm_blk_n = blk_strm_full_n;
    end else begin
        blk_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((end_len_strm_empty_n == 1'b0) | ((blk_strm_full_n == 1'b0) & (ap_predicate_op102_write_state9 == 1'b1))) & (1'b1 == ap_CS_fsm_state9) & (ap_predicate_op102_write_state9 == 1'b1))) begin
        blk_strm_din = or_ln489_s_fu_522_p5;
    end else if ((~(((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd0)) | ((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd1))) & (1'b1 == ap_CS_fsm_state8) & (cmp116_reg_668 == 1'd1))) begin
        blk_strm_din = or_ln467_s_fu_484_p18;
    end else if ((~(((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd0)) | ((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd1))) & (1'b1 == ap_CS_fsm_state8) & (cmp116_reg_668 == 1'd0))) begin
        blk_strm_din = or_ln471_s_fu_447_p17;
    end else if ((~((blk_strm_full_n == 1'b0) & (icmp_ln343_fu_315_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln343_fu_315_p2 == 1'd1))) begin
        blk_strm_din = or_ln365_1_fu_360_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        blk_strm_din = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_din;
    end else begin
        blk_strm_din = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_din;
    end
end

always @ (*) begin
    if (((~((end_len_strm_empty_n == 1'b0) | ((blk_strm_full_n == 1'b0) & (ap_predicate_op102_write_state9 == 1'b1))) & (1'b1 == ap_CS_fsm_state9) & (ap_predicate_op102_write_state9 == 1'b1)) | (~(((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd0)) | ((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd1))) & (1'b1 == ap_CS_fsm_state8) & (cmp116_reg_668 == 1'd0)) | (~(((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd0)) | ((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd1))) & (1'b1 == ap_CS_fsm_state8) & (cmp116_reg_668 == 1'd1)) | (~((blk_strm_full_n == 1'b0) & (icmp_ln343_fu_315_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln343_fu_315_p2 == 1'd1)))) begin
        blk_strm_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        blk_strm_write = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_write;
    end else begin
        blk_strm_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        end_len_strm_blk_n = end_len_strm_empty_n;
    end else begin
        end_len_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((end_len_strm_empty_n == 1'b0) | ((blk_strm_full_n == 1'b0) & (ap_predicate_op102_write_state9 == 1'b1))) & (1'b1 == ap_CS_fsm_state9)) | (~((end_len_strm_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        end_len_strm_read = 1'b1;
    end else begin
        end_len_strm_read = 1'b0;
    end
end

always @ (*) begin
    if ((((end_flag_3_reg_211 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((end_flag_3_reg_211 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        end_nblk_strm_blk_n = end_nblk_strm_full_n;
    end else begin
        end_nblk_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_155)) begin
        if ((end_flag_3_reg_211 == 1'd1)) begin
            end_nblk_strm_din = 1'd1;
        end else if ((end_flag_3_reg_211 == 1'd0)) begin
            end_nblk_strm_din = 1'd0;
        end else begin
            end_nblk_strm_din = 'bx;
        end
    end else begin
        end_nblk_strm_din = 'bx;
    end
end

always @ (*) begin
    if (((~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        end_nblk_strm_write = 1'b1;
    end else begin
        end_nblk_strm_write = 1'b0;
    end
end

always @ (*) begin
    if ((~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((end_flag_3_reg_211 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        len_strm_blk_n = len_strm_empty_n;
    end else begin
        len_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        len_strm_read = 1'b1;
    end else begin
        len_strm_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        msg_strm_read = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_msg_strm_read;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        msg_strm_read = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_msg_strm_read;
    end else begin
        msg_strm_read = 1'b0;
    end
end

always @ (*) begin
    if (((end_flag_3_reg_211 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        nblk_strm_blk_n = nblk_strm_full_n;
    end else begin
        nblk_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        nblk_strm_write = 1'b1;
    end else begin
        nblk_strm_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((end_len_strm_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (end_flag_3_reg_211 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((blk_strm_full_n == 1'b0) & (icmp_ln343_fu_315_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln343_fu_315_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if ((~((blk_strm_full_n == 1'b0) & (icmp_ln343_fu_315_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln343_fu_315_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~(((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd0)) | ((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd1))) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~((end_len_strm_empty_n == 1'b0) | ((blk_strm_full_n == 1'b0) & (ap_predicate_op102_write_state9 == 1'b1))) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((end_len_strm_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = (((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5 = ((blk_strm_full_n == 1'b0) & (icmp_ln343_fu_315_p2 == 1'd1));
end

always @ (*) begin
    ap_block_state8 = (((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd0)) | ((blk_strm_full_n == 1'b0) & (cmp116_reg_668 == 1'd1)));
end

always @ (*) begin
    ap_block_state9 = ((end_len_strm_empty_n == 1'b0) | ((blk_strm_full_n == 1'b0) & (ap_predicate_op102_write_state9 == 1'b1)));
end

always @ (*) begin
    ap_condition_155 = (~(((end_flag_3_reg_211 == 1'd0) & (end_nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (nblk_strm_full_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd0) & (len_strm_empty_n == 1'b0)) | ((end_flag_3_reg_211 == 1'd1) & (end_nblk_strm_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2));
end

always @ (*) begin
    ap_predicate_op102_write_state9 = ((icmp_ln343_reg_664 == 1'd0) & (cmp116_reg_668 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign blk_num_fu_304_p2 = (select_ln299_fu_296_p3 + zext_ln299_fu_282_p1);

assign cmp116_fu_320_p2 = ((left_reg_641 < 6'd56) ? 1'b1 : 1'b0);

assign grp_fu_255_p4 = {{len_reg_634[60:29]}};

assign grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg;

assign grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg;

assign icmp_ln299_fu_290_p2 = ((left_fu_264_p1 > 6'd55) ? 1'b1 : 1'b0);

assign icmp_ln343_fu_315_p2 = ((left_reg_641 == 6'd0) ? 1'b1 : 1'b0);

assign left_fu_264_p1 = len_strm_dout[5:0];

assign nblk_strm_din = blk_num_fu_304_p2;

assign or_ln365_1_fu_360_p2 = (or_ln365_s_fu_352_p3 | 512'd2147483648);

assign or_ln365_fu_336_p2 = (or_ln_fu_325_p5 | 512'd2147483648);

assign or_ln365_s_fu_352_p3 = {{tmp_24_fu_342_p4}, {32'd0}};

assign or_ln467_s_fu_484_p18 = {{{{{{{{{{{{{{{{{trunc_ln485_reg_647}, {3'd0}}, {grp_fu_255_p4}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_16_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_15_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_14_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_13_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_12_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_11_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_10_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_9_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_8_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_7_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_6_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_5_out}}, 
    {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_4_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_out}};

assign or_ln471_s_fu_447_p17 = {{{{{{{{{{{{{{{{grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_18_out}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_17_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_16_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_15_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_14_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_13_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_12_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_11_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_10_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_9_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_8_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_7_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_6_out}}, 
    {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_5_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_4_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_out}};

assign or_ln489_s_fu_522_p5 = {{{{trunc_ln485_reg_647}, {3'd0}}, {tmp_1_reg_688}}, {448'd0}};

assign or_ln_fu_325_p5 = {{{{trunc_ln485_reg_647}, {3'd0}}, {grp_fu_255_p4}}, {448'd0}};

assign rev_fu_374_p2 = (tmp_fu_367_p3 ^ 1'd1);

assign select_ln299_fu_296_p3 = ((icmp_ln299_fu_290_p2[0:0] == 1'b1) ? 59'd2 : 59'd1);

assign select_ln375_fu_391_p3 = ((cmp116_reg_668[0:0] == 1'b1) ? 4'd7 : 4'd8);

assign start_out = real_start;

assign tmp_24_fu_342_p4 = {{or_ln365_fu_336_p2[511:32]}};

assign tmp_fu_367_p3 = len_reg_634[32'd2];

assign trunc_ln299_fu_286_p1 = len_strm_dout[1:0];

assign trunc_ln485_fu_268_p1 = len_strm_dout[28:0];

assign trunc_ln_fu_272_p4 = {{len_strm_dout[63:6]}};

assign zext_ln299_fu_282_p1 = trunc_ln_fu_272_p4;

endmodule //top_module_preProcessing
